language: python
python:
    - "3.6"

stages:
  - lint
  - test

install:
    - pip install -r requirements-dev.txt

jobs:
    include:
        - stage: lint
          script: tox -e lint
        - stage: test
          script: tox -e test

after_success:
    coveralls
